language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dshurick
  password:
    secure: fmzqTE3mrlnFgDx8qifAw+wsVZmidA9gvsOyE9a4+JkYZwEmq/m6ocDykCnrn0aY6U4yjDALSB0mPklR+QvgbP/Hr4oNVRWOdRa1IdXNMBOTAqgROxZODBklzN4ADdlF4uKlLx4WrKD16+4Rs+8t0mLgv9z0SghBFFv/hp/L4I6NpmoOJlZ9g/c13pXDVtZ48BpoKVp/w/s2/U7uHb9JhtG/YNzgYZ2wXvQMBV7i10AgqVeJMOVuxHLnMUY35GuIHM4oomtddIsFsLLytzKFXsXN0COm/dYy1kkY8GspQl11cU+LZ8mh0Zeam+J3lOa7qxsy6fY4LZEkOuQhDGYT814TqdFHaUO+rTPDmZrTPuXSUGt4KnB3KxoMydztKnX1NT/fYRExu5rbWVaDmFZr27KVHXohLmkCiRGt+RZrMn5Ls2xegZ2WX1mJecxFhRZRwoiIUywhUKKI/K2JrC1HYHz6Go0XP42IJ+MllgVjSbwaXXLl0FluMNlYkF/VgxuNT4ruQzjs7dJvRr9KPxlF3SaTUI5tXmIWQpw3VpvPjV1JDjc5O8Gqf8TVN8fKXQ2D+FlNWo9TRwWsfAB41g+KGBJaEqoNgui9JQMsIv+/Mti9nGA7aBN/1W9n5AyKO2zIelVfF7EfTKiAxi4opotAgaa/5SE4fAkyvwlq9cEhMOk=
  on:
    tags: true
    repo: dshurick/hyper_sklearn
    python: 3.6
